### ISSUE TITLE
Create RFC around Github and PR etiquette

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/docs#21]
How do authors and reviewers interact with PRs? Document the standard process that we typically have used here at CDS.
(Usually authors merge, review required before merging, whether we prefer squash and merge, whether or when we want design approval or when just dev is enough, etc etc). I have my own opinions about a lot of these, based on how I've operated since being at CDS, but I am sure these would be better if discussed and agreed upon by other folks.

Also put in guidelines for how reviewers and reviewees should act towards each other in a PR review. I know paul had some documentation around this that was excellent. I will try to find it.

**Comment by dj2** [comment]
This is a great idea. When you've got some time can you put some of your opinions here so we can start to collate them? Some of mine would be:

 * Authors merge
   * Author is in best position to know if there are any slight changes or followups before merge
 * Use squash and merge
    * The history of the development is captured in the PR. Working commits usually have less useful commit messages which aren't useful in the main repo
  * Code review is required. (Do we want some kind of carve out for a to-be-reviewed for emergencies?)
  * The purpose of code review is to get to a good state. The code doesn't have to be perfect you're aiming for a LGTM (looks good to me). Note the good, not perfect, not excellent, but good.
  * Escalate if the review is blocked
  * Even if you can't review, put a comment in the PR if it's going be longer then 24hrs before you do review to let the author either switch reviewers, or have an idea of when they'll hear back.
  * When reviewing, try to stick to questions as opposed to giving orders. You don't know what the author has thought of or planned for. It's better to ask if they considered something, as they may have rejected it already, then to tell them to use it and have then try to explain why not.

**Comment by brdunfield** [comment]
I agree with much of your opinions. Here's mine more specifically:

- Authors merge
- Squash and merge preferred
- I like having github auto delete branches after they've been merged, as I don't like merged branches cluttering up the repo
- Code review required, with at least one reviewer. Always at least 1 dev reviewer, and ideally have at least one design reviewer on anything front-facing or content.
- Author should link the PR to any tracked issues or trello cards. Author should also include any context around whether the issue has been broken down into several PRs and justification for where they've chosen to break it up. Next steps are great to include in this situation as well (as well as being tracked in their appropriate issue).
- Author should include any steps to test, caveats, or gotchas that the reviewer will need to understand the PR.
- I am not a huge fan of commenting your own PR through github - if you need to include comments to explain something in the PR, these should more often than not be code comments.
- Reviewers should point out the good as well as the bad - if the author has done something particularly well, reviewers should point it out as a well done.
- +1 to the questions vs orders for reviewers, always seek clarification on why something was done a certain way as opposed to assuming.

I'm still trying to dig up that PR etiquette documentation. Will look more today.

**Comment by brdunfield** [comment]
Found it!
https://github.com/cds-snc/cra-claim-tax-benefits/blob/main/docs/CODE-REVIEW-GUIDELINES.md
