### ISSUE TITLE
Create RFC for SRE shared responsibility model

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/docs#27]
We are at a stage where we would like community input for our shared responsibility model between SRE and the rest of CDS (particularly the developer community.

Here is a link that will inform the RFC:
https://github.com/cds-snc/site-reliability-engineering/blob/main/documents/shared_responsibility.md

**Comment by dj2** [comment]
This has been added in https://github.com/cds-snc/docs/pull/28.
