### ISSUE TITLE
Questions regarding enforcement.

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/docs#4]
1. Who is responsible for making sure employees follow these RFC's? 

3. What happens if folks don't follow the RFC? 

*Edited to remove redundant question

**Comment by dj2** [comment]
I can see some of these coming up in response to need. I'm not sure how prescriptive we need to be to start.

1. We as a community are responsible. During code reviews, design reviews, etc. If there are practices we think are good as a community that aren't being followed then there should at least be a discussion as to why not.

2. See 1, I think it's basically the same answer.

3. If an RFC isn't being followed by the majority of folks, then I'd argue the RFC is wrong, needs to be retired and possibly a followup RFC written that captures how the community is working. I don't think an RFC should ever be considered static, these can, and probably should change as circumstances change.

**Comment by wmoussa-cds** [comment]
great question and should be move to the Discussion board..I will do so if no objection

**Comment by dj2** [comment]
Yea, seems like it could be good as a discussion so it's easier to see the answer in the future. (And, I can see it as an evolving answer as we refine the process)

**Comment by wmoussa-cds** [comment]
created https://github.com/cds-snc/docs/discussions/6
